### ISSUE TITLE
Add example of using a LangChain tool to the docs

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/ControlFlow#222]
### Enhancement Description

Would show a user how to add common pre-built tools. 
It took me a bit to get this to work. 

### Use Case

Say a user wants to get up-to-date information into their app. You can do this with the `DuckDuckGoSearchRun` tool.

### Proposed Implementation

```Python
Create an example that shows how to use the `DuckDuckGoSearchRun` LangChain tool.
```

**Comment by jlowin** [comment]
I think this is done!
