### ISSUE TITLE
Support langchain 0.3

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/ControlFlow#319]
### Enhancement Description

LangChain 0.3 finally adds Pydantic 2 support, so we can clean up the backend significantly

**Comment by kingabzpro** [comment]
@jlowin you are working over time. 🤫😅

**Comment by jlowin** [comment]
🫡

**Comment by kingabzpro** [comment]
> 🫡

Would love to collaborate with you in the future. I have been eagerly waiting for someone who shares my passion for problem-solving and matches my energy.
